### PR TITLE
Fix 'fw-info' version display issue.

### PR DESCRIPTION
**Pull request by xyan264**
Function 'dev->ops->get_fw_version' gets current firmware version of the local PAX device only. If user is running 'fw-info' on a remote PAX device, the version displayed is incorrect. We should use the version info from 'switchtec_fw_part_summary()' instead to determine current running firmware version.

Function 'print_fw_part_info' is re-structured to maintain program output consistency.

### CODE REVIEW

**Comment by kelvin-cao** [comment]
I think we should update the switchtec_get_fw_version() to make it leveraging switchtec_fw_part_summary() to get the fw version.

**Comment by lsgunth** [comment]
Yes, switchtec_get_fw_version() might be unusable... 

The only other caller of switchtec_get_fw_version() is print_dev_info()... If it is also broken in the same way than it seems like the existing switchtec_get_fw_version() is not useful.

**Comment by xyan264** [comment]
Closed in favor of alternative approach.

**Comment by kelvin-cao** [comment]
Yes, in theory user can get the version info by switchtec_fw_part_summary(). But to keep the compatibility, let's still keep the switchtec_get_fw_version() and just fix it by making it leveraging switchtec_fw_part_summary().

**Pull request closed without merging**
