### PR TITLE
Enable C++ compilation

### PR DESCRIPTION
**Pull request by Floessie**
Hi,

This PR renames a parameter that collides with a C++ keyword (`new`) and makes the library usable in C++ projects.

Best,
Flössie

### CODE REVIEW

**Comment by wesleywesley** [comment]
@Floessie 
Pls create your bug fix branch based on the latest devel branch.

Per our pull request process, we merge pull request into our devel branch first. I have change the target branch from microsemi:master to microsemi:devel.

And pls run "root/scripts/checkpatch.pl" for your patch, to make sure no error/warning exists.

Regard,
Wesley

**Comment by Floessie** [comment]
Now I'm a bit puzzled. Maybe I should have read `CONTRIBUTING.md` earlier. :wink: 

Is this the right way to get this fix in?

1. Drop this PR.
2. Fork `lsgunth/switchtec-user` as per `CONTRIBUTING.md`.
3. Branch off from `devel` (which doesn't exist in `lsgunth/switchtec-user`).
4. Make changes.
5. Run `root/scripts/checkpatch.pl` against `git diff`.
6. Commit with a better commit message (is "Fix compilation with C++ compiler by replacing C++ keyword" better?).
7. Create PR against `lsgunth/switchtec-user`.

**Comment by wesleywesley** [comment]
1. Drop this PR. 
-- It's ok.

2. Fork lsgunth/switchtec-user as per CONTRIBUTING.md.
3. Branch off from devel (which doesn't exist in lsgunth/switchtec-user).
-- checkout -b "bug_fix_xxx" branch from microsemi/devel

4. Make changes.
5. Run root/scripts/checkpatch.pl against git diff.
-- generate patch file by "git format-patch"
-- run checkpatch.pl with the patch, fix the errors and warnings if required

6. Commit with a better commit message (is "Fix compilation with C++ compiler by replacing C++ keyword" better?).
-- Yes, this make sure you pass the checkpatch.pl check

7. Create PR against lsgunth/switchtec-user.
-- again microsemi/devel

**Comment by Floessie** [comment]
@wesleywesley 
> 1. Drop this PR.
-- It's ok.

One can't change the source branch of a PR on GitHub, so I'm forced to start a new PR and drop this one.

Thanks for the hints. I'll follow them in the new PR.

Maybe you should include this info in `CONTRIBUTING.md`.

**Comment by Floessie** [comment]
@wesleywesley To which `checkpatch.pl` are you referring? Can't find it anywhere in the tree.

**Comment by wesleywesley** [comment]
path: root/scripts/checkpatch.pl

example:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/checkpatch.pl?h=v5.1-rc1

**Comment by Floessie** [comment]
Using the `checkpatch.pl` you linked results in

```
Must be run from the top-level dir. of a kernel tree
```

Does this mean I have to checkout the kernel to provide you with a PR for a user space library?

**Comment by wesleywesley** [comment]
@Floessie 
If you agree, I will adopt your changes and create a new pull request, but follow the process we setup.

regard,
Wesley

**Comment by Floessie** [comment]
@wesleywesley Sure, I'm fine with you adopting the changes. The scope of #80 was making you aware of a real concern: Using the library within a C++ project (there are reasons to use C++, e.g. GUI toolkits like Qt, Gtkmm, or wxWidgets) is currently impossible. The proposed patch was one way to fix that.

I was urged by Logan to turn the patch into a PR without being aware of the procedure to follow. Even if I had read `CONTRIBUTING.md` I would have got it wrong, because `CONTRIBUTING.md` doesn't describe the rules you had me to follow here. If you search for `checkpatch` within this repository this issue here is the only one mentioning it. If you want contributors to use `checkpatch` you should probably think about shipping a customized version of it with the project (others do that, too). And please, do correct `CONTRIBUTING.md` so that the next contributor won't look like a fool.

Thanks,
Flössie

**Comment by wesleywesley** [comment]
@Floessie 
Thx for your suggestion.

**Comment by wesleywesley** [comment]
#85 is updated version of this patch, so close this one.

**Pull request closed without merging**
