### PR TITLE
Map the entire gas space twice for two different section

### PR DESCRIPTION
**Pull request by wesleywesley**
new F/W GAS_READ_MRPC command could be used to access(r/w)
GAS space which beyond GAS MRPC section, so limit the scope
to the first 4K bytes of GAS space

### CODE REVIEW

**Comment by lsgunth** [comment]
Nak -- you may be breaking things that have already been used by users. For example, the 'switchtec gas' commands become completely useless after this change. 

You need to still map the entire GAS which means probably two mmap calls. You also *must* make sure it works in a backwards compatible way: which means it must work with the original kernel and the new kernel with the WC MRPC region.

Logan

**Comment by wesleywesley** [comment]
original kernel with iomap, set the whole gas as UC-(uncached minus), but it worked with user tool by 
/device/resouce0_wc WC.
But it exist a aliasing issue.

**Comment by lsgunth** [comment]
???

 You didn't address any of my concerns.

**Comment by lsgunth** [comment]
Ick, no. Please see ca79cc178cd5e167df720902f631de6b9595ae98 for how this should be done. Note it's only very lightly tested and may need some fallback code or something in some cases.

Logan

**Comment by wesleywesley** [comment]
@lsgunth 
thx.
We will test this patch on both UC- and WC+UC- driver.

**Comment by lsgunth** [comment]
Thanks, also please ensure it passes Travis. I didn't do that.

**Comment by wesleywesley** [comment]
@lsgunth it pass Travis-ci check. pls approve. thx.

**Comment by wesleywesley** [comment]
@lsgunth thx.

**Pull request merged**
