### PR TITLE
Display of ltssm minor states in switchtec status command

### PR DESCRIPTION
**Pull request by vermilionink**
This code change verified as described in jira PSBUMWX-107

### CODE REVIEW

**Comment by wesleywesley** [comment]
@vermilionink 

Thx for you commits.

Some suggestions:

1. Pls based on the latest microsemi/devel branch.
The commits before Update switchtec.c mess the patch.

2. While on the other aspect, I think the two commits should be Update switchtec.h first, and Update switchtec.c second.
Update switchtec.h is the bug fix, it is necessary, while Update switchtec.c is optional.

regard,
Wesley

**Comment by wesleywesley** [comment]
@vermilionink

Add suggestions:
1. Pls supply meaningful commit message[1].
2. Sign your work [2]



[1]2) Describe your changes
https://www.kernel.org/doc/html/v4.16/process/submitting-patches.html#describe-your-changes
[2]11) Sign your work - the Developer’s Certificate of Origin
https://www.kernel.org/doc/html/v4.16/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Comment by wesleywesley** [comment]
@vermilionink 
It is better that the patch ready before 3/22, so that we can include it into the nearest release.

**Comment by vermilionink** [comment]
Hello Wesley,
Thank you for the instructions. I have submitted the changes under #79.
Jason

**Pull request closed without merging**
